function [Q, A, M] = actionManager(S, Mprev, Mnet, EPSILON)
%ACTIONMANAGER Selcts (and executes) an action for the manager
%
%   Parameters
%   ==========
%   S            - vector (agent's state, one-hot)
%   MPREV        - vector (agent's previous motivation towards each city)
%   MNET         - DLNetwork (deep Q-model)
%   EPSILON      - double (percent of random decisions)
%   Q            - vector (action values)
%   A            - number (next action generated by the model)
%   M            - vector (agent's new motivation towards each city)
%
%   Author
%   ======
%   Ngoc Tran,      2018-2019. ntran@cshl.edu
%   Sergey Shuvaev, 2019-2021. sshuvaev@cshl.edu

%Computing the Q-values
len = length(Mnet);
Mnet(1).setInput([S, Mprev]);
for j = 2 : len - 1
    stepForward(Mnet, j);
end
Q = Mnet(len - 1).y;

%Epsilon-greedy action choice
[~, A] = max(Q);
if rand < EPSILON
    A = randi(length(Q));
end

%Updated estimate of the agent's motivation
M = Mprev;
if A ~= length(Q)
    M(A) = 0;
end
